inference_config_path: "config/inference/inference.yaml"
video_path: "videos/demo2.mp4"
question: "Inpaint the man on the right."
possible_anwsers: None
skip_mem_build: False
with_two_mem: True
seed: 12345
max_answer: 1
max_try: 7
