# config.yaml
openai:
  AGENT_GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_MODEL_NAME : "gpt-3.5-turbo"
  GPT_API_KEY: "sk-..."
  PROXY: "localhost:..."

google_cloud:
  CLOUD_VISION_API_KEY: null
  QUOTA_PROJECT_ID: null

mcts_planner:
  good_base_reward: 1.0
  bad_base_reward: -1.0
  decay_rate: 0.5

memory:
  step: 30
  memory_list:
    - "VideoInstanceUnderstanding_cuda:0"
    - "VideoTemporalUnderstanding_cuda:0"

tool:
  TOP_K: 2
  tool_list:
    - "TemporalTool_cpu"
    - "CountingTool_cpu"
    - "ReasonFinder_cpu"
    - "HowSeeker_cpu"
    - "DescriptionTool_cpu"
    - "DefaultTool_cpu"
    - "InpaintingTool_cuda:0"



